### ISSUE TITLE
Crashes if no game is present

### ISSUE THREAD

**Issue by melzyy** [Crementif/SteamRPC#2]
![image](https://user-images.githubusercontent.com/71926357/209476688-cbc4bc43-8dd7-47b7-ac11-34d2d42b0237.png)
Any way of fixing besides endlessly autorestarting?

**Comment by Crementif** [comment]
Should be fixed in the latest update. Do note that this project currently doesn't support any games yet and that the warzone profile is just an initial start that still needs finishing.

Someone did ask me to update the project and said that he'd work on some profiles (at least for MF2/Warzone) but he hasn't done them yet. Maybe soon!

**Comment by melzyy** [comment]
i forked your repo and made it for mw2 only with most modes and maps added, you can check it out if you want haha

**Comment by Crementif** [comment]
Oh cool, would you be willing to merge it into this repository? Or maybe you wanted to work on it a bit more?

**Comment by melzyy** [comment]
i think ive done mostly what i wanted, just havent done raids and coops
i wanted to link you the map icons so you can upload them to your discord application but ive deleted the originals
i took the images from here https://www.gamesatlas.com/cod-modern-warfare-2/maps/ and just cropped them to the center
